### ISSUE TITLE
List item: separate items for blank line.

### ISSUE THREAD

**Issue by tsuyoshicho** [sarisia/actions-readme-feed#1]
## problem

Qiita post rss feed is split.

see [view and source](https://github.com/tsuyoshicho/tsuyoshicho/blob/master/README.adoc)

rendered html source copy
```html
<ul>
<li>
<p>Nov 19: <a href="https://qiita.com/tsuyoshi_cho/items/756818c2e430a6635010" rel="nofollow">Vimプラグイン開発でCI</a></p>
</li>
<li>
<p>Nov 03: <a href="https://qiita.com/tsuyoshi_cho/items/bdade529e8ebc2a05b6a" rel="nofollow">vim-jpの活動とプラグインとヘルプファイル</a></p>
</li>
<li>
<p>Aug 28: <a href="https://qiita.com/tsuyoshi_cho/items/01b772da7fda2f1c3ce7" rel="nofollow">git のマージコンフリクト時の BASE,LOCAL,REMOTE</a></p>
</li>
<li>
<p>Apr 10: <a href="https://qiita.com/tsuyoshi_cho/items/9af7a81cc51af17a611f" rel="nofollow">Travis OrgからComへの変更</a></p>
</li>
<li>
<p>Mar 30: <a href="https://qiita.com/tsuyoshi_cho/items/d9f077c2c1b075f2b99e" rel="nofollow">gitのやりなおし、特殊ケース</a></p>
</li>
</ul>
```

---

## solution

Markdown,asciidoc and other, list item need no separate items for blank line.
(Because, these items around p - 1 paragraph per item.)

GitHub Action support multi-line text, if user need split line to show you how to use it.
(multi-line [example](https://github.com/tsuyoshicho/action-vimlint/blob/840dd7b1e73191a658f69167f456c84f62c3b8fb/.github/workflows/depup.yml#L25-L28))

## example

no blank

- a
- b
- c

```
- a
- b
- c
```

at blank

- a

- b

- c

```
- a

- b

- c
```

**Comment by sarisia** [comment]
Hi @tsuyoshicho ,
thank you for raising the issue!

Unfortunately, I'm not sure what is the problem current version have, 
same for the desired behavior.

I believe the `format` option can handle most of the use cases,
so, can you provide the value of the `format` option which causes the issue?

**Comment by sarisia** [comment]
Just FYI: using Japanese is welcome too!

**Comment by tsuyoshicho** [comment]
了解です。

たしかにソースを見直すと、空白なく生成できているので、どちらかというとGitHubのasciidocのレンダリングが問題だったようです。

おさわがせしました...。
