### ISSUE TITLE
Ordering feed by date

### ISSUE THREAD

**Issue by Wikunia** [sarisia/actions-readme-feed#2]
Not all rss feeds are ordered by date. Would it be possible to order them by `pubDate`?

**Comment by sarisia** [comment]
Hi @Wikunia , thank you for raising a suggestion!
It is implemented in [v1.2.0](https://github.com/sarisia/actions-readme-feed/releases/tag/v1.2.0) which was released just now.
Please take a look, and if you still have a problem, feel free to reopen the issue!

**Comment by Wikunia** [comment]
Thanks that works perfectly :tada:
