### ISSUE TITLE
two job warnings happen

### ISSUE THREAD

**Issue by tsuyoshicho** [sarisia/actions-readme-feed#234]
Now (2022/11/26) two job warnings happen.

* Node 12 using in actions : `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16:`
* set-output using in actions : see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Thanks

**Comment by sarisia** [comment]
Thank you for let me know. Will release an update soon!

**Comment by sarisia** [comment]
The fix is now released as v1.8.0.

Thank you for let me know!

https://github.com/sarisia/actions-readme-feed/releases/tag/v1.8.0
